//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.PRODUCTS_ORDERS = new HashSet<PRODUCTS_ORDERS>();
        }
    
        public int ID { get; set; }
        public int ID_Customer { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTS_ORDERS> PRODUCTS_ORDERS { get; set; }
    }
}
